version: '3.5'
services:
  fuseki:
    image: semapps/jena-fuseki-webacl
    volumes:
      - './data/fuseki:/fuseki'
      - './data/staging:/staging'
    ports:
      - '3030:3030'
    networks:
      - semapps
    environment:
      ADMIN_PASSWORD: admin

  fuseki_compact:
    image: semapps/jena-fuseki-webacl:latest
    entrypoint: /docker-compact-entrypoint.sh
    profiles:
      - compact
    volumes:
      - ./data/fuseki:/fuseki

  middleware:
    build:
      context: ./../archipelago-build-dockerhub/
      dockerfile: Dockerfile.mid
    container_name: middleware
    depends_on:
      - fuseki
      - redis
      - keycloak
    volumes:
      - './middleware/logs:/archipelago/middleware/logs'
      - './middleware/jwt:/archipelago/middleware/jwt'
      - './middleware/uploads:/archipelago/middleware/uploads'
      - ./addOn:/archipelago/middleware/addOn
    environment:
      - 'SEMAPPS_SPARQL_ENDPOINT=http://fuseki:3030/'
      - SEMAPPS_MAIN_DATASET=localData
      - SEMAPPS_JENA_USER=admin
      - SEMAPPS_JENA_PASSWORD=admin
      - 'SEMAPPS_HOME_URL=http://localhost:3000/'
      - 'SEMAPPS_OIDC_ISSUER=http://keycloak:8080/auth/realms/DP/'
      - SEMAPPS_OIDC_CLIENT_ID=semapps
      - 'SEMAPPS_REDIS_URL=redis://redis:6379/0'
    command: bash -c "cp -r ./addOn/middleware/* . && pm2-runtime 'yarn run dev'"
    networks:
      - semapps
    ports:
      - '3000:3000'

  frontend:
    build:
      dockerfile: ./../archipelago-build-dockerhub/Dockerfile.front
    environment:
      - 'REACT_APP_MIDDLEWARE_URL=http://localhost:3000/'
      - REACT_APP_MAPBOX_ACCESS_TOKEN=MyMapBoxToken
      - PORT=4000
    volumes:
      - ./addOn:/archipelago/frontend/addOn
    command: bash -c "cp -r ./addOn/frontend/* . && yarn install && yarn start"
    networks:
      - semapps
    ports:
      - '4000:4000'

  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - './data/redis_data:/data'
    networks:
      - semapps
    command:
      - redis-server
      - '--appendonly'
      - 'yes'

  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm-export.json
      KEYCLOAK_FRONTEND_URL: 'http://localhost:8080/auth'
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
    depends_on:
      - postgres
    volumes:
      - './realm-export.json:/tmp/realm-export.json'
    ports:
      - '8080:8080'
    networks:
      - semapps

  postgres:
    image: postgres
    volumes:
      - './keycloak/postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - semapps
networks:
  semapps:
    name: semapps_network
